[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/rybbit3"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/rybbit3/"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://youtube.com/@YOUR_USERNAME"

    [social.params]
        icon = "brand-youtube"
